- hosts: all
  become: true
  tasks:
  - name: update 
    apt: 
      update_cache: yes
  
  - name: upgrade
    apt:
       upgrade: dist

  - name: install docker dependencies
    apt:
      name: 
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
  
  - name: add docker gpg key
    apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg

  - name: add docker repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable

  - name: install docker
    apt:
      name:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io

  - name: update
    shell: sudo apt update

  - name: install docker-compose
    shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

  - name: set permission for docker
    shell: sudo chmod +x /usr/local/bin/docker-compose

  - name: setup docker command without sudo
    shell: sudo usermod -aG docker ubuntu
